name: New Students Api Pipeline

on: [push]

jobs:
  hello:
    name: "Show our code"
    runs-on: ubuntu-latest
    env:
      NAME: ${{secrets.NAME}}
      WORLD: "Earth"
    steps:
      - uses: actions/checkout@v2
      - name: Show the directory
        run: ls
      - name: Show the index.ts
        run: cat index.ts
      - name: Say hello
        run: echo "Hello $NAME and $WORLD"

  # test:
  #   name: "Test our API"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run Tests
  #       run: npm run test
