name: New Students Api Pipeline

on:
  push:
    branches:
      - main

jobs:
  hello:
    name: "Show our code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show the directory
        run: ls
      - name: Show the index.ts
        run: cat index.ts

  test:
    name: "Test our API"
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm run test
