name: New Students Api Pipeline

on:
  push:
    branches:
      - main

jobs:
  hello:
    name: "Hello World"
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World"
      - name: Say Goodbye
        run: echo "Goodbye"
      - name: Print Node Version
        run: node --version

  # test:
  #   name: "Test our API"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run Tests
  #       run: npm run test
